In [1]:
import pandas as pd

# Load the dataset
file_path = r"c:\Users\ASUS\Downloads\Nutrition,_Physical_Activity,_and_Obesity_-_Behavioral_Risk_Factor_Surveillance_System_202512.csv"
df = pd.read_csv(file_path)

# Check the first few rows to make sure it loaded correctly
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\ASUS\\Downloads\\Nutrition,_Physical_Activity,_and_Obesity_-_Behavioral_Risk_Factor_Surveillance_System_202512.csv'

In [ ]:
# Display the first 5 rows
print("First 5 rows")
display(df.head())

First 5 rows

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$15,000 - $24,999",INC,INC1525
1,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$25,000 - $34,999",INC,INC2535
2,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$35,000 - $49,999",INC,INC3550
3,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$50,000 - $74,999",INC,INC5075
4,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.840571122, -86.631860762)",OWS,OWS1,Q036,VALUE,1,Income,"$75,000 or greater",INC,INC75PLUS

In [ ]:
# Check data types and column names
print("Data Info")
df.info()

Data Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110880 entries, 0 to 110879
Data columns (total 33 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   YearStart                   110880 non-null  int64
 1   YearEnd                     110880 non-null  int64
 2   LocationAbbr                110880 non-null  object
 3   LocationDesc                110880 non-null  object
 4   Datasource                  110880 non-null  object
 5   Class                       110880 non-null  object
 6   Topic                       110880 non-null  object
 7   Question                    110880 non-null  object
 8   Data_Value_Unit             4620 non-null    object
 9   Data_Value_Type             110880 non-null  object
 10  Data_Value                  97666 non-null   float64
 11  Data_Value_Alt              97666 non-null   float64
 12  Data_Value_Footnote_Symbol  13214 non-null   object
 13  Data_Value_Footnote         13214 non-null   object
 14  Low_Confidence_Limit        97666 non-null   float64
 15  High_Confidence_Limit       97666 non-null   float64
 16  Sample_Size                 97666 non-null   object
 17  Total                       3960 non-null    object
 18  Age(years)                  23760 non-null   object
 19  Education                   15840 non-null   object
 20  Sex                         7920 non-null    object
 21  Income                      27720 non-null   object
 22  Race/Ethnicity              31680 non-null   object
 23  GeoLocation                 108864 non-null  object
 24  ClassID                     110880 non-null  object
 25  TopicID                     110880 non-null  object
 26  QuestionID                  110880 non-null  object
 27  DataValueTypeID             110880 non-null  object
 28  LocationID                  110880 non-null  int64
 29  StratificationCategory1     110880 non-null  object
 30  Stratification1             110880 non-null  object
 31  StratificationCategoryId1   110880 non-null  object
 32  StratificationID1           110880 non-null  object
dtypes: float64(4), int64(3), object(26)
memory usage: 27.9+ MB

In [ ]:
# Check for null values in each column
print("Null Value Count")
print(df.isnull().sum())

Null Value Count
YearStart                          0
YearEnd                            0
LocationAbbr                       0
LocationDesc                       0
Datasource                         0
Class                              0
Topic                              0
Question                           0
Data_Value_Unit               106260
Data_Value_Type                    0
Data_Value                     13214
Data_Value_Alt                 13214
Data_Value_Footnote_Symbol     97666
Data_Value_Footnote            97666
Low_Confidence_Limit           13214
High_Confidence_Limit          13214
Sample_Size                    13214
Total                         106920
Age(years)                     87120
Education                      95040
Sex                           102960
Income                         83160
Race/Ethnicity                 79200
GeoLocation                     2016
ClassID                            0
TopicID                            0
QuestionID                         0
DataValueTypeID                    0
LocationID                         0
StratificationCategory1            0
Stratification1                    0
StratificationCategoryId1          0
StratificationID1                  0
dtype: int64

In [ ]:
# List of columns to drop
cols_to_drop = [
    'Data_Value_Alt',              # Duplicate of Data_Value
    'Data_Value_Unit',             # Mostly null / implied
    'Data_Value_Footnote_Symbol',  # Metadata for null values
    'Data_Value_Footnote',         # Metadata for null values
    'Total', 'Age(years)',         # Sparse columns (info is in Stratification columns)
    'Education', 'Sex', 
    'Income', 'Race/Ethnicity' 
]

# Create a clean copy by dropping these columns
df_clean = df.drop(columns=cols_to_drop)

print(f"Dropped columns: {cols_to_drop}")

Dropped columns: ['Data_Value_Alt', 'Data_Value_Unit', 'Data_Value_Footnote_Symbol', 'Data_Value_Footnote', 'Total', 'Age(years)', 'Education', 'Sex', 'Income', 'Race/Ethnicity']

In [ ]:
# Count rows before dropping
rows_before = len(df_clean)

In [ ]:
# Drop rows where 'Data_Value' is NaN
df_clean = df_clean.dropna(subset=['Data_Value'])

In [ ]:
# Calculate dropped rows
rows_after = len(df_clean)
print(f"Rows before: {rows_before}")
print(f"Rows after: {rows_after}")
print(f"Dropped {rows_before - rows_after} rows with missing data values.")

Rows before: 110880
Rows after: 97666
Dropped 13214 rows with missing data values.

In [ ]:
# Remove commas and convert Sample_Size to float
# We use .astype(str) first to handle any potential non-string types safely
df_clean['Sample_Size'] = df_clean['Sample_Size'].astype(str).str.replace(',', '').astype(float)

# Verify the change
print("Sample_Size data type is now:", df_clean['Sample_Size'].dtype)
display(df_clean[['LocationDesc', 'Data_Value', 'Sample_Size']].head())

Sample_Size data type is now: float64

  LocationDesc  Data_Value  Sample_Size
0      Alabama        34.8       1367.0
1      Alabama        35.8        757.0
2      Alabama        32.3        861.0
3      Alabama        34.1        785.0
4      Alabama        28.8       1125.0

In [ ]:
# Reset index to have continuous row numbers
df_clean = df_clean.reset_index(drop=True)

# Final check of the clean dataframe
print("Final Cleaned Data Info")
df_clean.info()

# df_clean.to_csv('Cleaned_Nutrition_Data.csv', index=False)
# print("Cleaned dataset saved to 'Cleaned_Nutrition_Data.csv'")

Final Cleaned Data Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97666 entries, 0 to 97665
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   YearStart                  97666 non-null  int64
 1   YearEnd                    97666 non-null  int64
 2   LocationAbbr               97666 non-null  object
 3   LocationDesc               97666 non-null  object
 4   Datasource                 97666 non-null  object
 5   Class                      97666 non-null  object
 6   Topic                      97666 non-null  object
 7   Question                   97666 non-null  object
 8   Data_Value_Type            97666 non-null  object
 9   Data_Value                 97666 non-null  float64
 10  Low_Confidence_Limit       97666 non-null  float64
 11  High_Confidence_Limit      97666 non-null  float64
 12  Sample_Size                97666 non-null  float64
 13  GeoLocation                95653 non-null  object
 14  ClassID                    97666 non-null  object
 15  TopicID                    97666 non-null  object
 16  QuestionID                 97666 non-null  object
 17  DataValueTypeID            97666 non-null  object
 18  LocationID                 97666 non-null  int64
 19  StratificationCategory1    97666 non-null  object
 20  Stratification1            97666 non-null  object
 21  StratificationCategoryId1  97666 non-null  object
 22  StratificationID1          97666 non-null  object
dtypes: float64(4), int64(3), object(16)
memory usage: 17.1+ MB

In [ ]:
# Check for null values in the cleaned dataset
print("Null Values After Cleaning")
null_counts = df_clean.isnull().sum()
print(null_counts)

# Optional: Visualize if there are any remaining nulls
if null_counts.sum() == 0:
    print("\nSuccess: No missing values remaining in the dataset!")
else:
    print("\nNote: There are still some missing values (e.g., in GeoLocation).")
    # Show columns that still have nulls
    print(null_counts[null_counts > 0])

Null Values After Cleaning
YearStart                       0
YearEnd                         0
LocationAbbr                    0
LocationDesc                    0
Datasource                      0
Class                           0
Topic                           0
Question                        0
Data_Value_Type                 0
Data_Value                      0
Low_Confidence_Limit            0
High_Confidence_Limit           0
Sample_Size                     0
GeoLocation                  2013
ClassID                         0
TopicID                         0
QuestionID                      0
DataValueTypeID                 0
LocationID                      0
StratificationCategory1         0
Stratification1                 0
StratificationCategoryId1       0
StratificationID1               0
dtype: int64

Note: There are still some missing values (e.g., in GeoLocation).
GeoLocation    2013
dtype: int64

In [ ]:
# Filter out rows with missing GeoLocation (removes 'National' level data)
df_clean = df_clean.dropna(subset=['GeoLocation'])

# Reset the index again after dropping rows
df_clean = df_clean.reset_index(drop=True)

# Verify that there are no nulls left in GeoLocation
print(f"Nulls in GeoLocation: {df_clean['GeoLocation'].isnull().sum()}")
print(f"Unique locations remaining: {df_clean['LocationAbbr'].nunique()}")

Nulls in GeoLocation: 0
Unique locations remaining: 54

In [ ]:
# Save the final cleaned dataset
df_clean.to_csv('Cleaned_Nutrition_Data_Map_Ready.csv', index=False)
print("File saved successfully as 'Cleaned_Nutrition_Data_Map_Ready.csv'")

File saved successfully as 'Cleaned_Nutrition_Data_Map_Ready.csv'

In [ ]:
# Check for null values one last time
print("Final Null Value Check")
final_nulls = df_clean.isnull().sum()
print(final_nulls)

Final Null Value Check
YearStart                    0
YearEnd                      0
LocationAbbr                 0
LocationDesc                 0
Datasource                   0
Class                        0
Topic                        0
Question                     0
Data_Value_Type              0
Data_Value                   0
Low_Confidence_Limit         0
High_Confidence_Limit        0
Sample_Size                  0
GeoLocation                  0
ClassID                      0
TopicID                      0
QuestionID                   0
DataValueTypeID              0
LocationID                   0
StratificationCategory1      0
Stratification1              0
StratificationCategoryId1    0
StratificationID1            0
dtype: int64